name: CI/CD

on:
  push:
    branches:
      - dev
      - release/*
  pull_request:
    branches:
      - dev
      - release/*

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install environment
        run: |
          date
          make environment
      - name: Run tests
        run: |
          date
          make test
          date
  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Build image
        run: |
          date
          make build
      - name: Upload image
        env:
          IMAGE_REPOSITORY_TOKEN: ${{ secrets.IMAGE_REPOSITORY_TOKEN }}
          IMAGE_REPOSITORY_URL: ${{ secrets.IMAGE_REPOSITORY_URL }}
          IMAGE_REPOSITORY_USER: ${{ secrets.IMAGE_REPOSITORY_USER }}
        run: |
          date
          make upload
          date
